---
kind: secret
name: AWS_ACCESS_KEY_ID
get:
  path: kv/data/minio
  name: AWS_ACCESS_KEY_ID
---
kind: secret
name: AWS_SECRET_ACCESS_KEY
get:
  path: kv/data/minio
  name: AWS_SECRET_ACCESS_KEY
---
kind: secret
name: docker_username
get:
  path: kv/data/dreg
  name: username
---
kind: secret
name: docker_password
get:
  path: kv/data/dreg
  name: password
---
kind: pipeline
type: kubernetes
name: test-container

dns_config:
  options:
    - name: ndots
      value: 1

steps:
  - name: build
    image: plugins/docker
    service_account: drone-runner
    environment:
      SCCACHE_ENDPOINT: "https://s3.vsix.me:9000"
      SCCACHE_BUCKET: "sccache"
      SCCACHE_S3_USE_SSL: "true"
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    settings:
      repo: dreg.vsix.me:9443/ndots-webhook
      registry: dreg.vsix.me:9443
      build_args_from_env: 
        - SCCACHE_ENDPOINT
        - SCCACHE_BUCKET
        - SCCACHE_S3_USE_SSL
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password

