apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ndots-webhook-config
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: CABUNDLE
    service:
      name: ndots-webhook
      namespace: ndots-webhook
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  name: ndots.vsix.me
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
