apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ndots-webhook-config
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0ekNDQW9tZ0F3SUJBZ0lRRlNDWjlzeXlTSTltenVPeVloSWs5VEFLQmdncWhrak9QUVFEQWpBak1TRXcKSHdZRFZRUUREQmhyTTNNdGMyVnlkbVZ5TFdOaFFERTFPRFUyTnpjMU9EWXdIaGNOTWpBeE1USTNNakEwTkRBMQpXaGNOTWpFeE1USTNNakEwTkRBMVdqQTRNVFl3TkFZRFZRUURFeTF1Wkc5MGN5MTNaV0pvYjI5ckxtNWtiM1J6CkxYZGxZbWh2YjJzdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFET2JvRm5TSFdvcFZ0ZGQrNDVuclc2UUpUNzFBTkw0OEhWaXpPQWJsQlZ5ejQxampSawpNYTM4aDdpdjlFUmxZZDA2Q25EQlhaN3EwUzZRS3UwanhKUS81akhYeHB5WWJ1bERoeE1jdkpwVk1TS2VKUXdCCkxicWI1eFFURFpsSFZpNDErWWFCWDZTZi9GTTBKSlh1NjBhd2tiQ1BZUUZwSWpXWkMzS2ZjZE9MUTY0M0Q3L24KTVhTS0ZVbm8zcTFIWjlaUzdHYmlrTU5jUjl3VWJsZ1FHV3VxMWtWM2dseEFMaG52dG1Eb1RqSUNNWEVTSThoUQowZDZkdE1SZzUvUlZKRThWNnBXLzBGd3VtSDBHajFGOVE2Rnprb3cvb3hoOVBUNFhkeTNrQXlsK0JVQUMxRXNiCmVXRUlZVnVtZzJqNTlxTmdZd3dkcHdROERPU1diZ3JJRDJPSkFnTUJBQUdqZ2I0d2dic3dEZ1lEVlIwUEFRSC8KQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdnWVVHQTFVZApFUVIrTUh5Q0RXNWtiM1J6TFhkbFltaHZiMnVDRzI1a2IzUnpMWGRsWW1odmIyc3VibVJ2ZEhNdGQyVmlhRzl2CmE0SWZibVJ2ZEhNdGQyVmlhRzl2YXk1dVpHOTBjeTEzWldKb2IyOXJMbk4yWTRJdGJtUnZkSE10ZDJWaWFHOXYKYXk1dVpHOTBjeTEzWldKb2IyOXJMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNQW9HQ0NxR1NNNDlCQU1DQTBnQQpNRVVDSVFDYnNtaXZXQTFKaldLbHNDR1J5N2dmbGNla3FXYkZUYVdPWGY3aXBHbFpJZ0lnZGZ2M3BBL3hrSFlTClVEVTNnWjZJQ0xYRzltMmRTTUlkek1JMUJHWUFtYVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K 
    url: "https://ndots-webhook.ndots-webhook.svc.cluster.local:8443/mutate"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: ndots.vsix.me
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - kube-system
    - key: name
      operator: NotIn
      values:
      - ndots-webhook
  objectSelector:
    matchExpressions:
    - key: ndots.vsix.me/mutate
      operator: NotIn
      values:
      - skip
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
