apiVersion: v1
kind: Service
metadata:
  name: ndots-webhook
  namespace: ndots-webhook
spec:
  ports:
  - name: ndots-webhook
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ndots-webhook
  sessionAffinity: None
  type: ClusterIP
